"""Add tonight field to Profile model

Revision ID: 0613f0e9519f
Revises: caeac9069b95
Create Date: 2024-08-10 13:33:00.424981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0613f0e9519f'
down_revision = 'caeac9069b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tonight', sa.Boolean(), nullable=True))
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('tonight')

    # ### end Alembic commands ###
